### ISSUE TITLE
UI Automation COMBO BOX and Web elements Not working 

### ISSUE THREAD

**Issue by akeshJohn** [OpenBotsAI/OpenBots.Studio#169]
1.Not able to capture Combo Boxes and select items depending on Index or Values.

2.Capture of Web Elements are working fine **but not able to increment the XPATH(or any other attributes)** to dynamically capture  different elements in a website during Bot Execution.

3. Open Bots studio interface often throws exception with a dialog box and will be forced to close the Application.

4. Mouse movement gets stuck during editing different commands in the Open Bots studio.(when the cursor is pointed outside the studio its normal movement is regained)

**Comment by openbots-ch** [comment]
Good Evening Akesh,

If you are currently on the develop branch some of the above issues are to be expected. The implementation of types had pretty severe effects on our UI, and we have received a lot of reports from our testing team that we are actively working through. We have a few pending pull requests that address some of these changes. Once these are merged I would recommend re-pulling and building. 

The second reported issue would ideally be handled through the use of variable embedding in the XPath string. I'll confirm that we are pre-processing those strings for variable insertions and let you know if we need to make a correction there.

We have seen issues where the interface will throw exceptions intermittently. These can be a nightmare to resolve, as there's often no solid reproduction steps. Before we package the upcoming release we are planning a long stress test with the debugger on to catch some of these intermittent issues and correct them. If you are able to nail down any causes please feel free to report them here, and we will gladly resolve them!

To your fourth point, is this repeatable through certain actions, or does it just occur at random points?
