### ISSUE TITLE
Variable size limit

### ISSUE THREAD

**Issue by jaribeiro73** [OpenBotsAI/OpenBots.Studio#189]
Hi,

I am reading a CSV file and store its content to a variable. However, OpenBots Studio 1.3.1 cannot read the file or save the content in the variable (I do not know where the problem is), if the file is more than 70kB.

**Comment by openbots-ch** [comment]
We have opened up a ticket internally to get this resolved. Thank you for the detailed report. I will follow up here once we have identified and resolved the issue.

**Comment by openbots-ch** [comment]
Hello, Unfortunately despite trying some very large files, and even attempting to introduce special values into the mix we have been unable to reproduce the error. Would you be able to pass through the file your are utilizing, and the script file with the failing code?
