### ISSUE TITLE
Trying to create new command. Importing nuget package fails to find references

### ISSUE THREAD

**Issue by nickproud** [OpenBotsAI/OpenBots.Studio#207]
I am trying to add a new nuget package which contains a new command (using Script Command class)
The command is a new OCR command which references the Tesseract library which it is itself using as a package, therefore Tesseract is a package dependency.

I create a local NuGet repository which the studio can see in the package manager:
![image](https://user-images.githubusercontent.com/15985202/113277516-b60f9d80-92d8-11eb-9047-350c7322ae34.png)
As you can see, the Tesseract dependency is listed as expected. 

Also, the command shows just fine in the list after loading the project. However, if I attempt to run the command, the OpenBots NuGet manager cannot resolve the Tesseract dependency

![image](https://user-images.githubusercontent.com/15985202/113277690-e6efd280-92d8-11eb-9f76-30629aab2ff7.png)

Essentially this means I can add my own commands just fine, but if those commands attempt to reference any dependencies, they will fail with the above error. 

I tested the nuget package I created in a different ,NET Framework project and I was able to reference the dependencies without error, so it seems to be something out the way packages are loaded into Openbots. 

Can anybody shed any light on this?

**Comment by openbots-ff** [comment]
Hello Nick, 

Thank you for reaching out to us. Currently, OpenBots Studio v1.4.0 is unable to load the dependencies of packages that aren't also referenced by the studio itself. Tesseract is not a dependency of the studio and therefore cannot be found by it. We've been working around this by adding these sub-dependency references to the studio project directly, but recent changes have been made that should resolve this issue in v1.4.1. 

Additionally, the development of a new suite of OCR commands has been included in our current release cycle. We estimate that v1.4.1 will be out by the end of the month.

**Comment by nickproud** [comment]
Thanks for the quick response. I'll give it a go. Loving the solution so thanks for the support.
