### ISSUE TITLE
Updated Sample Scripts

### ISSUE THREAD

**Issue by mark05e** [OpenBotsAI/OpenBots.Studio#219]
Would the sample scripts be updated anytime soon?

https://github.com/OpenBotsAI/OpenBots.Studio/tree/develop/OpenBots.Studio/Sample%20Scripts

**Comment by openbots-ch** [comment]
Hello Mark,

I've gone ahead and added a work item internally to replace the existing sample scripts with a few updated sample projects. We have quite a few created internally for demonstration purposes, and will likely replace what is currently there with those. I'll update you here when this has been done.

**Comment by mark05e** [comment]
Thank you

**Comment by openbots-ch** [comment]
Hello Mark,

As of #231 the sample scripts have now been updated for v1.4.0. We will occasionally update these scripts to align to new versions with signification differences.
