### ISSUE TITLE
How do initialize a variable?

### ISSUE THREAD

**Issue by avalosleonardo** [OpenBotsAI/OpenBots.Studio#256]
I'm looking around the OpenBots Studio and I can't figure out how to initialize a variable (in my case, a blank DataTable). I tried setting the value to {new System.Data.DataTable()} as well as many variations of this. I see that an older version of OpenBots has a New Variable Command, but this seems to be missing from the current 1.4.0 . I also checked out the Run Custom Code command, but I can't seem to get it to import System.Data. Am I missing something or is this not supported? Is there a way around it?

**Comment by openbots-ff** [comment]
Hello avalosleonardo,

There are a couple of potential scenarios depending on the version of Studio you're using, given that we've made some major changes between 1.4.0 and 1.5.0.

In the case that you're using the 1.4.0 studio, complex objects can only be initialized using the appropriate object commands. The variable value column should be left blank. In the case of DataTables, you would use the Create DataTable command. Any DataTable manipulation would also require the use of the appropriate commands. 

As of 1.5.0, we've fully implemented inline C# development, so you can can just set it to: new System.Data.DataTable() or new DataTable(). Creation/Manipulation of DataTables can still be done with commands, or with C# using the updated Set Variable/Evaluate Snippet Commands. We've recently moved our development to Azure so the 1.5.0 studio in github is behind by about a week, but we'll be updating the github source code after every major release. For 1.5.0, that will probably be this weekend.

**Comment by avalosleonardo** [comment]
> Hello avalosleonardo,
> 
> There are a couple of potential scenarios depending on the version of Studio you're using, given that we've made some major changes between 1.4.0 and 1.5.0.
> 
> In the case that you're using the 1.4.0 studio, complex objects can only be initialized using the appropriate object commands. The variable value column should be left blank. In the case of DataTables, you would use the Create DataTable command. Any DataTable manipulation would also require the use of the appropriate DataTable commands.
> 
> As of 1.5.0, we've fully implemented inline C# development, so you can can just set it to: new System.Data.DataTable() or new DataTable(). Creation/Manipulation of DataTables can still be done with commands, or with C# using the updated Set Variable/Evaluate Snippet Commands. We've recently moved our development to Azure so the 1.5.0 studio in github is behind by about a week, but we'll be updating the github source code after every major release. For 1.5.0, that will probably be this weekend.

Thank you so much for the prompt reply. But, I was actually looking for a Create New Datatable command, and I could not find one. I see in the DataTable Commands section has things to manipulate an existing DataTable, but not one to create a new one. Do I need to install any additional packages? I have all the packages that come by default in the project, but there's no New Datatable command in my list.

**Comment by openbots-ff** [comment]
That is very strange. Could you please provide us with a screenshot of the expanded DataTable Commands? The Create DataTable Command is part of the DataManipulation package so it's odd that the other commands would load and it wouldn't. One way you could try to reinstall the packages would be by deleting all the folders/files in this directory (C:\Users\{user}\AppData\Local\OpenBots Inc\packages) and reopening the studio. It should detect that the packages have been removed and reinstall them.

**Comment by avalosleonardo** [comment]
> That is very strange. Could you please provide us with a screenshot of the expanded DataTable Commands? The Create DataTable Command is part of the DataManipulation package so it's odd that the other commands would load and it wouldn't. One way you could try to reinstall the packages would be by deleting all the folders/files in this directory (C:\Users\{user}\AppData\Local\OpenBots Inc\packages) and reopening the studio. It should detect that the packages have been removed and reinstall them.

Actually, that fixed it. Thanks!
