### ISSUE TITLE
Native Chrome Messaging - JS Injection - popup issue

### ISSUE THREAD

**Issue by burque505** [OpenBotsAI/OpenBots.Studio#257]
**Studio version:** 1.5.2
**Platform:** Win10 Pro 64-bit 10.0.19043
**Description of issue:** 
Creating an alert by JS injection causes the Chrome instance to stop responding to user keyboard or mouse input, as modal alert has taken control. Alert cannot be dismissed. Clicking "OK" causes popup to flicker, but there is otherwise no response. The browser must be closed by the user to continue.
![alert_code](https://user-images.githubusercontent.com/46876254/127355320-b6cda190-3a86-4b7a-84a1-0cfe8734d760.PNG)
![script_shot](https://user-images.githubusercontent.com/46876254/127355435-30b91862-5bfc-4ee4-97f0-9f86ee242ba2.PNG)

**Comment by openbots-ch** [comment]
Thank you for the bug report. I've gone ahead and created an item internally to investigate this. We will get back with our findings once we take it up, and barring any technical limitations can provide a fix in a coming release.

**Comment by openbots-ch** [comment]
Hello, we have just pushed an update to the extension that should correct this issue. Once Chrome has updated the extension on your end it should work as expected!

**Comment by burque505** [comment]
@openbots-ch, thank you very much. The extension is updated and works as expected.

**Comment by burque505** [comment]
@openbots-ch, thank you very much. It is working as expected, extension version 1.6.0.3.
Regards, burque505
