### ISSUE TITLE
Not able to add task variable

### ISSUE THREAD

**Issue by TTBDevAdmin** [OpenBotsAI/OpenBots.Studio#43]
Hi,
i am not able to add a task variable in Run Task. UI doesn't show an option to add a variable in Task Variables section. I am using OpenBot studio v1.1.0 

![image](https://user-images.githubusercontent.com/54854919/99314265-d3aeff80-282e-11eb-9a74-45542ebcbc9b.png)

**Comment by openbots-ff** [comment]
Hello, 

The "Run Task" command loads existing variables in the "Options" > "Variable Manager" of the file being loaded. They act as arguments for the invoked tasks. It may just be that the file you're attempting to load has no variables yet.

**Comment by TTBDevAdmin** [comment]
thanks for the information. I was able to add variables.
Can we assign the Out variable value to the local variable of the calling task?
![image](https://user-images.githubusercontent.com/54854919/99427939-03fca980-28d4-11eb-9599-428fc98f0a0e.png)
I tried this way and it didn't assign value to {SourceFileName}

**Comment by openbots-ff** [comment]
The "Variable Value" parameter is for assigning default **values** to the invoked task's variables. By setting "Variable Return" to "Yes", {FieldValue} will be added to the original engine after "Run Task" finishes executing. You can either assign it to a new variable using a "New/Set Variable" command, or continue to manipulate it as {FieldValue}.

**Comment by TTBDevAdmin** [comment]
thanks
