### ISSUE TITLE
Schedule of tasks in OpenBots Studio doesn't work

### ISSUE THREAD

**Issue by jaribeiro73** [OpenBotsAI/OpenBots.Studio#54]
Hi,

I tried to schedule a task using OpenBots Studio schedule feature and it isn't possible. The feature demands that the file/task to run is in My Scripts folder (like taskt). However, this isn't the logic of OpenBots. So, this feature needs to be fixed.

**Comment by openbots-ff** [comment]
Hello,

Thank you for bringing this issue to our attention. We'll include a fix for the scheduler in OpenBots Studio v1.2 which will be released in mid December.

**Comment by openbots-ch** [comment]
Hello @jaribeiro73, we have updated the Task Scheduler in v1.2 to properly execute schedule project tasks. You are also able to delete created tasks. Please let us know if you have any issues execution a scheduled task and we will assist!
