### ISSUE TITLE
New Encryption methods pose issue

### ISSUE THREAD

**Issue by cyborgdoom** [OpenBotsAI/OpenBots.Studio#82]
OK think you guys backed yourself into a corner here... I noticed both in the agent and here in the studio the encryption and decryption methods use the system mac address as a key...

This poses an issue where you would have to have both the studio and the agent installed on the same machine... Which some may not want to. 

Is the intention to not allow the agent and studio to be on different machines?

**Comment by openbots-ch** [comment]
Good Afternoon,

An important thing to note is that the Studio is dependent on an Agent connection to utilize Server functionality, while the Agent can operate independently without a corresponding Studio installation. The credentials being stored in the Registry only apply to the current Agent installation, matching a Server instantiated Agent. The intent is that each Server provisioned Agent will correlate to a single installation instance tied to a AD account, with the required connection credentials stored locally and encrypted.  

We have considered adding separate connection functionality to the Studio, but believe that the Agent itself does not represent significant overhead to setup, and will serve a significant purpose in how we enable Server-Deployed attended automations for user machines. This encryption method will likely be adjusted soon, as well as our usage of the Window's Registry, as we seek to create a compatible version of the Agent for Linux. 

It's important to note as well that the ProtectedData methods we are now utilizing are inherently machine specific for their encryption, with the machine key simply acting as additional entropy in this case. This change does not affect the relationship between Agents and Studios, but instead enhances the overall security of the encryption by no longer utilizing a static stored key.

**Comment by openbots-ch** [comment]
Also, I have just created an OpenBots.Documentation repository to store design documentation for reference. Currently we have a significant amount of Server design documentation, and are a bit lacking on the Studio/Agent side. I'll be sure to create a document that addresses the intended relationship between the products, and how they interact to include there.

**Comment by cyborgdoom** [comment]
OK think that made sense ... is the intention to move to .net 5 / .net standard / .net core . if wanting to run on linux?

**Comment by openbots-ch** [comment]
The plan is to move the Agent over to .Net Core 3.1 first, as it doesn't rely on quite as many things as the Studio does. We plan a full jump top .Net 5 within the next few months, but have some significant dependencies to resolve to get there.
