### ISSUE TITLE
Install .net framework4.8 fail

### ISSUE THREAD

**Issue by Himan000** [OpenBotsAI/OpenBots.Studio#89]
when install OpenBots Studio， error occur as below. What happen?

> Unable to create or save new files in the folder into which
> the files are being extracted. Please check the folder properties
> to ensure you have permission on the folder to
> write files and that the folder is not read-only.

**Comment by Himan000** [comment]
I installed .net framework manually and no above error occured. But another error occur.

`Service 'OpenBotsSvc' (OpenBotsSvc) could not be installed.  Verify that you have sufficient privileges to install system services.`

**Comment by openbots-ch** [comment]
Good Afternoon,

I was able to recreate this issue while preparing our v1.2.1 release. I will respond here with a non-installer based fix if I can identify one, and will otherwise incorporate it into the 1.2.1 release coming very soon.

**Comment by openbots-ch** [comment]
Hello Himan00. I would recommending running the installation as administrator. It is likely that your account isn't able to install services as stated in the error message. I will attempt to reproduce the issue on my end as well.

**Comment by Himan000** [comment]
OK, I will try it. Thanks.

**Comment by Himan000** [comment]
Hi @openbots-ch ,
Itried running the installation as administrator, same error message occur.

**Comment by Himan000** [comment]
Hi @openbots-ch ，It seems that it's antivirus program problem. It works now after stop antivirus program. Thanks.
